title     = "Matt Snider"
baseURL   = "https://matt-snider.github.io/"
copyright = "© 2019 Matt Snider"

[params]
    full_name = "Matt Snider"
    job_title = "Software Developer"

    [params.social]
    github_url  = "https://github.com/matt-snider"
    gitlab_url  = "https://gitlab.com/matt-snider"
    keybase_url = "https://keybase.io/mattsnider"
    email_url   = "mailto:[myfirstname].[mylastname]@protonmail.com"

