title     = "Matt Snider"
baseURL   = "https://matt-snider.github.io/"
copyright = "© 2020 Matt Snider"

[params]
    full_name = "Matt Snider"
    job_title = "Software Developer"

    [params.social]
    github_url  = "https://github.com/matt-snider"
    gitlab_url  = "https://gitlab.com/matt-snider"
    keybase_url = "https://keybase.io/mattsnider"
    personal_url= "https://matt-snider.xyz"

    # Usually don't want to specify these
    email       = "[myfirstname].[mylastname]@protonmail.com"
    phone       = ""
    address     = ""

    [params.navigation]
    about    = "About"
    projects = "Projects"

[languages]

    [languages.en]
    weight = 1
    languageName = "English"

    [languages.de]
    weight = 2
    languageName = "Deutsch"

        [languages.de.params]
        job_title = "Software-Entwickler"

            [languages.de.params.navigation]
            about    = "About"
            projects = "Projekte"

